---
- become: yes
  hosts: all
  name: Setup new server

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Remove un-needed dependencies
      apt:
        autoremove: yes

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      register: result
      until: result is not failed
      delay: 5
      retries: 5

    - name: Update apt and install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker module for Python
      pip:
        name: docker

    - name: Check if a reboot is needed for Debian and Ubuntu servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the Debian or Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
